spring: 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student 
    username: ryoko
    password: postgres
server: 
  servlet:
    context-path: /ex-beginner